### PR TITLE
add date filter

### PR DESCRIPTION
**Pull request by kielni**
- add one option per day between now and Nov 8 to date filter select
- save mapsheet once it's ready
- on change date filter, hide markers that don't match selected date

### CODE REVIEW

**Comment by kielni** [comment]
date_filter

**Comment by kielni** [comment]
I'll try adding https://codepen.io/pudgereyem/pen/PqBxQx to materialize the select and make it look closer to the drive form

**Comment by kielni** [comment]
Marker is visible = `map.getBounds().contains(marker.getPosition())`

But would need to update on every bounds change

**Comment by wboykinm** [comment]
Lemme merge in the geocoder.

**Comment by wboykinm** [comment]
I think we're good here: 

hrc9

**Pull request merged**
